# Generated by Django 5.0.2 on 2024-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='link',
            field=models.CharField(max_length=64),
        ),
    ]
